config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
   
   get '/search', to: 'profiles#search'
  # get 'profiles/index'
    root "profiles#index"
    resources :profiles
     
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
	  has_one_attached :image
	

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         enum role: {male: 0,female: 1}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
	before_action :configure_permitted_parameters, if: :devise_controller?
	private
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:role])
	end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
        @female= Profile.where(gender:"female")
        @male= Profile.where(gender:"male")
        @profiles =Profile.all
  end

   def show
        @profile = Profile.find(params[:id])
   end

  def new
      @profile = Profile.new
  end

  def create
    #byebug
    @profile = Profile.new(profile_params)
      if @profile.save
        redirect_to @profile
      else
        render :new, status: :unprocesssble_entity
      end
  end

  def destroy
    @profile = Profile.find(params[:id])
    @profile.destroy
    redirect_to root_path, status: :see_other
  end
  
   # byebug
    def search
      @profile = params[:query]
      @profiles = Profile.where("profiles.first_name like ?", ["%#{@profile}%"])
      render :index
    end


private
  def profile_params
    params.require(:profile).permit(:first_name, :last_name, :gender, :address, :mobile_number, :hobbies, :father_name, :city, :pincode, :college_name, :job, :diet,:date_of_birth, :nationality, :religion, :marital_status, :income, :mother_name, :state, :about_yourself, :height,:image, :search)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Website</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-dark bg-dark" style="background-color: #E3F2FD;">
    <% if user_signed_in? %>
 <p class="text-white"> Logged in as</p>  <strong style="color:white"><%= current_user.email%></strong>
  <%#= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> 
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link text-white ' %>
  <form class="form-inline" action="/search" method="GET">
    <div class="container" class="justify-content-center">
    <div class="row height d-flex justify-content-center align-items-center">
          <table>
              <td><input type="/search" class="form-control me-12" placeholder="name" aria-label="Search"
            name="query" method = "GET"> </td>
              <td><button class="btn btn-primary col-md-12 " type="submit" >Search</button> </td>
          </table>
    </div>
    </div>
</form>
<% else %>
  <%#= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> 
  <%#= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>


<!-- </p> -->
</nav>

     <!-- <p class="notice"><%#= notice %></p>
       <p class="alert"><%#= alert %></p> -->

    <%= yield %>
  </body>
</html>

app/views/profiles/_form.html.erb
<h3>Profile</h3>
	<table>	
     <%= form_with(model: profile) do |form| %>
  <tr>

	<td>
		<div>
			<%= form.label :First_name %><br>
			<%= form.text_field :first_name %>
		</div>
	</td>

	<td>
		<div>
			<%= form.label :Last_name %><br>
			<%= form.text_field :last_name %>
		</div>
	</td>
  </tr>
<tr>

	<td>
		<div>
      		<%= form.label :Gender %><br/>
      		<%= form.select :gender, ["select one","male","female"] %>
  		</div>

	</td>

	<td>
		<div>
			<%= form.label :Date_of_birth %><br>
			<%= form.date_field :date_of_birth %>
		</div>
	</td>
</tr>
<tr>

	<td>
		<div>
      <%= form.label :Marital_status %><br/>
      <%= form.select :marital_status, ["select one","single","Married","widow"] %>
  </div>

	</td>

	<td>
		<div>
			<%= form.label :Father_name %><br>
			<%= form.text_field :father_name %>
		</div>
	</td>
</tr>
<tr>

	<td>
		<div>
			<%= form.label :Mother_name %><br>
			<%= form.text_field :mother_name %>
		</div>
	</td>

	<td>
		<div>
			<%= form.label :Mobile_number %><br>
			<%= form.text_field :mobile_number %>
		</div>
	</td>
</tr>
<tr>

	<td>
		<div>
      		<%= form.label :Religion %><br/>
      		<%= form.select :religion, ["select one","Hindu","Muslim","Sikh", "Christian"] %>
  		</div>
	</td>

	<td>
		<div>
			<%= form.label :Nationality %><br>
			<%= form.text_field :nationality %>
		</div>
	</td>
</tr>
<tr>

	<td>
		<%= form.label :State %><br>
		<%= form.text_field :state %>
		
	</td>

	<td>
		<div>
			<%= form.label :city %><br>
			<%= form.text_field :city %>
		</div>
	</td>
</tr>
<tr>

	<td>
		<div>
			<%= form.label :Address %><br>
			<%= form.text_field :address %>
		</div>
	</td>

	<td>
		<div>
			<%= form.label :Pincode %><br>
			<%= form.text_field :pincode %>
		</div>
	</td>
</tr>
<tr>

	<td>
		<div>
			<%= form.label :Height %><br>
			<%= form.text_field :height %>
		</div>
	</td>
</tr>
<tr>

	<td>
		<div>
      		<%= form.label :Diet %><br/>
      		<%= form.select :diet, ["select one","veg","non-veg"] %>
  		</div>
	</td>

	<td>
		<div>
			<%= form.label :Hobbies %><br>
			<%= form.text_area :hobbies %>
		</div>
	</td>
</tr>
<tr>

	<td>
		<div>
			<%= form.label :College_name %><br>
			<%= form.text_field :college_name %>
		</div>
	</td>

	<td>
		<div>
			<%= form.label :Job %><br>
			<%= form.text_field :job %>
		</div>
	</td>
</tr>
<tr>

	<td>
		<div>
			<%= form.label :Income %><br>
			<%= form.text_field :income %>
		</div>
	</td>

	<td>
		<div>
			<%= form.label :About_yourself %><br>
			<%= form.text_area :about_yourself %>
		</div>
	</td>
</tr>
<td>
		<div>
			<%= form.label :Profile_photo %><br>
			<%= form.file_field :image %>
		</div>
	</td>
</table>

<div>
	<%= form.submit %>
</div>
<% end %>

app/views/profiles/_search.html.erb
<!-- <form class="form-inline" action="/search" method="GET">
    <div class="container" class="justify-content-center">
    <div class="row height d-flex justify-content-center align-items-center">
          <table>
              <td>
                <input type="search" class="form-control" placeholder="first_name" aria-label="Search" name="query" method = "GET" class="form-control form-control-lg"> </td>
              <td><button class="btn btn-primary col-md-12 " type="submit" >Search</button ></td>
          </table>
    </div>
</div>
    </form> -->

app/views/profiles/index.html.erb
<h1 class="text-center">Basic Details </h1>

<%#= render partial: "search_bar/form" %>
      <div class="container">
      <table class="table table-light text-center">
   <thead>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Gender</th>
        <th> City</th>
        <th> </th>
    </thead>
 <% if current_user.role == "male" %> 
	<% @female.each do |profile| %>
      <tr>
         <%#= image_tag profile.image, :size =>"100", class: "rounded-circle " %>

          <td><%= profile.first_name %></td>
          <td><%= profile.last_name %></td>
          <td><%= profile.gender %></td>
          <td><%= profile.city %></td>
          <td><%= link_to "More details", profile,class:"btn btn-outline-success"%><br></td>
      </tr> 
  <% end %>
  <% else %>
  <% @male.each do |profile| %>
      <tr>
         <%#= image_tag profile.image, :size =>"100", class: "rounded-circle " %>

          <td><%= profile.first_name %></td>
          <td><%= profile.last_name %></td>
          <td><%= profile.gender %></td>
          <td><%= profile.city %></td>
          <td><%= link_to "More details", profile,class:"btn btn-outline-success"%><br></td>
      </tr> 
  <% end %>

  <% end %>

</table>
</div>

<div class="text-center">
<%= link_to 'New Profile Create', new_profile_path, class: "btn btn-danger"%> 
</div>
    

app/views/profiles/new.html.erb
<%= render "form", profile:@profile %>

app/views/profiles/show.html.erb
<h1 class="text-center">Profile Details </h1>
 

<div class="text-center">
<%= image_tag @profile.image, :align=> "middle", :size =>"100", class: "rounded-circle " %>
</div>
<div class= "text-center">
    <h1><%= @profile.first_name+" "+@profile.last_name  %></h1>
</div> 
<div class="container">
<h3>Profile</h3>
 <table>
  <thead>
    <tr>
      	<th scope="col">First Name</th>
      	<th scope="col">Last Name</th>
		    <th scope="col"> Gender</th>
		    <th scope="col"> Date_of_birth</th> 
    </tr>
  </thead>
  <tbody>
    <tr>
	  <td><%= @profile.first_name %></td>  
		<td><%=@profile.last_name %></td>
		<td><%= @profile.gender %></td>
		<td><%= @profile.date_of_birth %></td>
    </tr>
   
  </tbody>
</table>
</div>

<div class="container">
<h3>Personal</h3>
<table>
  <thead>
    <tr>
        <th scope="col">Nationality</th>
       <th scope="col"> Marital Status</th>
        <th scope="col">Religion</th>
        <th scope="col"> Father Name</th>
        <th scope="col">Mother Name</th>

    </tr>
  </thead>
  <tbody>
    <tr>
        <td><%= @profile.nationality %></td>
        <td><%= @profile.marital_status %></td>
        <td><%= @profile.religion %></td>
        <td><%= @profile.father_name %></td>
        <td><%= @profile.mother_name%></td>
    
    </tr>
  </tbody>
</table>
</div>

<div class="container">
<h3>Address</h3>
<table>
  <thead>
    <tr>
        <th scope="col">State</th>
        <th scope="col">City</th>
        <th scope="col">address</th>
       <th scope="col"> Pincode</th>
    </tr>
  </thead>
  <tbody>
    <tr>
        
        <td><%= @profile.state %></td>
        <td><%= @profile.city%></td>
        <td><%= @profile.address %></td>
        <td><%= @profile.pincode %></td>
    
    </tr>
  </tbody>
</table>
</div>

<div class="container">
<h3>Education & Work</h3>
<table>
  <thead>
    <tr>
        <th scope="col">College name</th>
        <th scope="col">Job</th>
        <th scope="col">Height</th>
        <th scope="col">Income</th>
    </tr>
  </thead>
  <tbody>
    <tr>
        <td><%= @profile.college_name %></td>
        <td><%= @profile.job %></td>
        <td><%= @profile.height %></td>
        <td><%= @profile.income %></td>
    </tr>
  </tbody>
</table>
</div>

<div class="container">
<h3>About & Hobbies</h3>
<table>
  <thead>
    <tr>
        <th scope="col">Hobbies</th>
        <th scope="col">About_yourself</th>
    </tr>
  </thead>
  <tbody>
    <tr>
        <td><%= @profile.hobbies %></td>
        <td><%= @profile.about_yourself %></td>
    </tr>
  </tbody>
</table>
</div>
<div class= "text-center">
<%= link_to "Destroy",profile_path(@profile), :method => :delete, class:'btn btn-danger', data: {
                            turbo_method: :delete,
                            turbo_confirm: "Are you sure?"
                          } %>
<%= link_to " Back", profiles_path,class: "btn btn-warning"%>
</div>





 

app/views/search_bar/_form.html.erb
<form class="form-inline" action="/search" method="GET">
    <div class="container" class="justify-content-center">
    <div class="row height d-flex justify-content-center align-items-center">
          <table>
              <td><input type="/search" class="form-control" placeholder="name" aria-label="Search"
name="query" method = "GET" class="form-control form-control-lg"> </td>
              <td><button class="btn btn-primary col-md-12  " type="submit" >Search</button> </td>
          </table>
    </div>
    </div>
</form>